server:
  servlet:
    contextPath: /
  port: ${PORT:8080}

eureka:
  instance:
    hostname: ${HOST:localhost}
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_ZONE:http://172.17.0.5:8761/eureka}

spring:
  zipkin:
    base-url: http://54.254.30.227:9411
    enabled: false
  application:
    name: zuul-api-gateway
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

zuul:
  routes:
    auth-service:
        path: /qpon-auth-service/**
        serviceId: qpon-auth-service
        stripPrefix: false
    otp-service:
        path: /qpon-otp-service/**
        serviceId: qpon-otp-service
        stripPrefix: false
    core-service:
      path: /qpon-core-service/**
      serviceId: qpon-core-service
      stripPrefix: false
    file-manager-service:
      path: /qpon-file-manager-service/**
      serviceId: qpon-file-manager-service
      stripPrefix: false
    util-service:
      path: /qpon-util-service/**
      serviceId: qpon-util-service
      stripPrefix: false


  sensitiveHeaders: Cookie,Set-Cookie

ribbon:
  ReadTimeout: ${RIBBON_TIMEOUT:60000}
  eager-load:
    enabled: true

accessControl:
  allowedOrigin: ${ALLOWED_ORIGIN:*}

logging:
  level:
    com.swivel.qpon: DEBUG