#deploy to framworkserver dev
name: Build and deploy zuul

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      #run: mvn -B clean install --file pom.xml
      run: mvn clean install -DskipTests

    - name: Copy Artifact via scp to server
      uses: appleboy/scp-action@master
      env:
        host: ${{ secrets.QA_SERVER }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
      with:
        source: "./target/qpon-zuul-service-0.0.1-SNAPSHOT.jar"
        target: "/home/ubuntu/tmp"

    - name: Executing remote command to run the service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.QA_SERVER }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
        envs:
          DBPass:${{ secrets.DBPASSDEV }}
        #script_stop: true
        script: |
         lsof -i :8080
         kill $(lsof -t -i:8080)
         cd /home/ubuntu/tmp/target
         nohup java -jar qpon-zuul-service-0.0.1-SNAPSHOT.jar >/dev/null 2>&1 &



